name: Build KernelSU Waydroid

on:
  workflow_dispatch:
    inputs:
      RootType:
        description: 'Escolha root (KernelSU / none)'
        required: true
        default: 'KernelSU'
      GAppsFlavor:
        description: 'Tipo de GApps (pico / nano / super)'
        required: true
        default: 'nano'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparar ambiente
        run: |
          sudo apt update && sudo apt install wget zip -y

      - name: Baixar system.img com KernelSU
        run: |
          wget -O system.img "https://waydroid-image-server.surge.sh/system-kernelsu.img"

      - name: Baixar vendor.img padrão
        run: |
          wget -O vendor.img "https://waydroid-image-server.surge.sh/vendor.img"

      - name: Compactar em ZIP final
        run: |
          zip kernelSU-waydroid.zip system.img vendor.img

      - name: Publicar artefatos
        uses: actions/upload-artifact@v3
        with:
          name: kernelSU-waydroid
          path: kernelSU-waydroid.zip
