name: KernelSU Waydroid Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Preparar ambiente
        run: |
          sudo apt update
          sudo apt install wget zip gzip -y

      - name: Baixar boot.img KernelSU (versão fixa confiável)
        run: | wget -O boot.img.gz "https://github.com/KernelSU-Next/KernelSU-Next/releases/download/v1.0.8/android12-5.10.233_2025-02-boot.img.gz"
    gunzip boot.img.gz
    mv boot.img system.img

      - name: Baixar vendor.img estável
        run: | wget -O vendor.img "https://github.com/waydroid-root/images/releases/latest/download/vendor.img"

      - name: Criar arquivo ZIP final
        run: |
          zip kernelSU-waydroid.zip system.img vendor.img

      - name: Publicar artefato ZIP no GitHub
        uses: actions/upload-artifact@v4
        with:
          name: kernelSU-waydroid
          path: kernelSU-waydroid.zip
