name: Build KernelSU Waydroid

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Preparar ambiente
        run: |
          sudo apt update && sudo apt install wget zip -y

      - name: Baixar system.img com KernelSU
        run: wget -O system.img https://waydroid-image-server.surge.sh/system-kernelsu.img

      - name: Baixar vendor.img
        run: wget -O vendor.img https://waydroid-image-server.surge.sh/vendor.img

      - name: Compactar arquivos
        run: zip kernelSU-waydroid.zip system.img vendor.img

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: kernelSU-waydroid
          path: kernelSU-waydroid.zip
